version: "3.2"

services:
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    environment:
      MSSQL_SA_PASSWORD: "MyPassword123!"  # Update the SA password here
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver-data:/var/opt/mssql
      - ./scripts:/scripts  # Mount local scripts directory to container
    #rofiles: ['main-app-service']

  python:
    container_name: app-python
    build: ./service
    ports:
      - 8001:80
    depends_on:
      - sql-server-db
    environment:
      - MSSQL_HOST="sql-server-db"
      - MSSQL_NAME="Combine"
      - MSSQL_SA_PASSWORD="MyPassword123!"  # Update the SA password here
    #profiles: ['app-py']


volumes:
  sqlserver-data:  # Define a named volume for SQL Server data
    driver: local  # Use the local volume driver for simplicity
