FROM python:3.10-slim-buster

WORKDIR /service

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

#RUN /bin/sh -c apt install unixodbc-dev 



# Update package lists
RUN apt-get update

# Install required packages
RUN apt-get install -y curl gnupg

# Import Microsoft GPG key
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -

# Add Microsoft repository for ODBC Driver 17 for SQL Server
RUN curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list

# Update package lists again
RUN apt-get update

# Install ODBC Driver 17 for SQL Server
RUN ACCEPT_EULA=Y apt-get install -y msodbcsql17

COPY app.py app.py

ENV PYTHONPATH /service

CMD [ "python3", "app.py"]